{
 "title": "API",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU average usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=~\"$job\"}[2m]) * 1000) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Database logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(http_requests_total{job=~\"$job\"}[1m]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "avg(rate(http_requests_error{job=~\"$job\"}[1m]))",
     "legendFormat": "Total errors"
    }
   ]
  },
  {
   "title": "Application logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=~\"$job\", job!=\"postgres\"} | json",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "limit": 100, "service": "api" }
   ]
  }
 ]
}