# Configuration file version
apiVersion: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      tlsAuth: false
    secureJsonData:
      password: ""
    version: 1
    editable: true
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    uid: jaeger
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    jsonData:
      tlsAuth: false
    secureJsonData:
      password: ""
    version: 1
    editable: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
    isDefault: false
